# Generated by Django 2.1 on 2018-10-04 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('school_grade', models.CharField(max_length=200, verbose_name='School and grade')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Date of birth')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Contact person')),
                ('parent_name', models.CharField(max_length=100, verbose_name='Name of coach/parent')),
                ('parent_phone', models.CharField(max_length=100, verbose_name='Phone of coach/parent')),
                ('parent_email', models.CharField(max_length=100, verbose_name='E-mail of coach/parent')),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_contest', models.CharField(max_length=100, verbose_name='Type of contest')),
                ('number_of_countries', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Number of countries participated')),
                ('date_of_the_contest', models.CharField(max_length=100, verbose_name='Date of the contest')),
                ('place_of_the_contest', models.CharField(max_length=100, verbose_name='Place of the contest')),
                ('kind_of_the_prize', models.CharField(max_length=100, verbose_name='Kind of the price')),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apply.Participant')),
            ],
            bases=('apply.participant',),
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apply.Participant')),
            ],
            bases=('apply.participant',),
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('participant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='apply.Participant')),
            ],
            bases=('apply.participant',),
        ),
        migrations.AddField(
            model_name='participant',
            name='prize',
            field=models.ManyToManyField(to='apply.Prize'),
        ),
    ]
