# Generated by Django 2.1 on 2018-10-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0003_auto_20181004_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='number_of_participants',
            field=models.DecimalField(blank=True, decimal_places=0, default=1, max_digits=6, verbose_name='Number of countries participated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='number_of_countries',
            field=models.DecimalField(decimal_places=0, max_digits=6, verbose_name='Number of countries participated'),
        ),
    ]
