# Generated by Django 2.1 on 2018-10-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0004_auto_20181007_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='number_of_countries',
            field=models.CharField(max_length=100, verbose_name='Number of countries participated'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='number_of_participants',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number of countries participated'),
        ),
    ]
