# Generated by Django 2.1 on 2018-10-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0005_auto_20181007_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='docs',
            field=models.FileField(default=1, upload_to='docs/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prize',
            name='number_of_participants',
            field=models.CharField(blank=True, max_length=100, verbose_name='Number of participants'),
        ),
    ]
