# Generated by Django 2.1 on 2018-10-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0008_auto_20181007_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='prize',
        ),
        migrations.AddField(
            model_name='participant',
            name='prize',
            field=models.ManyToManyField(to='apply.Prize'),
        ),
    ]
