# Generated by Django 2.1 on 2018-10-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apply', '0009_auto_20181007_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': 'Art'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='prize',
            options={'verbose_name_plural': 'Prize'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name_plural': 'Science'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name_plural': 'Sport'},
        ),
    ]
