# Generated by Django 2.1 on 2018-09-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_personcontacts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonContacts',
            new_name='PersonContact',
        ),
    ]
