# Generated by Django 2.1 on 2018-09-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180928_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personcontact',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
