# Generated by Django 2.1 on 2018-09-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100, verbose_name='Event name')),
                ('ticket_vendor', models.URLField()),
                ('first_screen_top_text', models.TextField(blank=True, verbose_name='First screen top text')),
                ('first_screen_img', models.ImageField(blank=True, upload_to='events_img', verbose_name='First screen image')),
                ('first_screen_bottom_text', models.TextField(blank=True, verbose_name='First screen bottom text')),
                ('second_screen_top_text', models.TextField(blank=True, verbose_name='Second screen top text')),
                ('second_screen_img', models.ImageField(blank=True, upload_to='events_img', verbose_name='Second screen image')),
                ('second_screen_bottom_text', models.TextField(blank=True, verbose_name='Second screen bottom text')),
                ('third_screen_text', models.TextField(blank=True, verbose_name='Third screen text')),
                ('third_screen_img', models.ImageField(blank=True, upload_to='events_img', verbose_name='Third screen image')),
                ('Fourth_screen_text', models.TextField(blank=True, verbose_name='Fourth screen text')),
                ('Fourth_screen_img', models.ImageField(blank=True, upload_to='events_img', verbose_name='Fourth screen image')),
            ],
        ),
    ]
