# Generated by Django 2.1 on 2018-09-29 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Fourth_screen_img',
            new_name='fourth_screen_img',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='Fourth_screen_text',
            new_name='fourth_screen_text',
        ),
    ]
