# Generated by Django 2.1 on 2018-09-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180919_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_banner', models.ImageField(blank=True, upload_to='banner_img', verbose_name='First banner')),
                ('second_banner', models.ImageField(blank=True, upload_to='banner_img', verbose_name='Second banner')),
                ('third_banner', models.ImageField(blank=True, upload_to='banner_img', verbose_name='Third banner')),
            ],
        ),
    ]
