# Generated by Django 2.1 on 2018-09-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='first_banner',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='second_banner',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='third_banner',
        ),
        migrations.AddField(
            model_name='banner',
            name='banner_img',
            field=models.ImageField(blank=True, upload_to='banner_img', verbose_name='Banner image'),
        ),
    ]
