# Generated by Django 2.1 on 2018-09-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20180921_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Banner name'),
            preserve_default=False,
        ),
    ]
