# Generated by Django 2.1 on 2018-09-22 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_banner_banner_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New',
            new_name='Story',
        ),
    ]
