# Generated by Django 2.1 on 2018-09-22 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180922_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='published_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
