# Generated by Django 2.1 on 2018-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='Product')),
                ('user_name', models.CharField(max_length=100, verbose_name='User name')),
                ('user_phone', models.CharField(max_length=100, verbose_name='User phone')),
                ('user_address', models.CharField(max_length=100, verbose_name='User address')),
                ('user_add_info', models.TextField(verbose_name='Additional information')),
            ],
        ),
    ]
