# Generated by Django 2.1 on 2018-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_email',
            field=models.EmailField(default=None, max_length=100, verbose_name='User e-mail'),
            preserve_default=False,
        ),
    ]
