# Generated by Django 2.1 on 2018-09-27 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_email',
            field=models.CharField(max_length=100, verbose_name='User e-mail'),
        ),
    ]
