# Generated by Django 2.1 on 2018-09-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20180927_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_name',
            field=models.CharField(max_length=100, verbose_name='Product name'),
        ),
    ]
