# Generated by Django 2.1 on 2018-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('status', models.CharField(max_length=100, verbose_name='Status')),
                ('img', models.ImageField(blank=True, upload_to='about_img', verbose_name='Image')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('full_description', models.TextField(verbose_name='Full description')),
                ('detail_page_title', models.CharField(max_length=100, verbose_name='Detail page title')),
            ],
        ),
        migrations.CreateModel(
            name='Foundation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('full_description', models.TextField(verbose_name='Full description')),
                ('detail_page_title', models.CharField(max_length=100, verbose_name='Detail page title')),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('full_description', models.TextField(verbose_name='Full description')),
                ('detail_page_title', models.CharField(max_length=100, verbose_name='Detail page title')),
                ('img', models.ImageField(blank=True, upload_to='about_img', verbose_name='Image')),
            ],
        ),
    ]
