# Generated by Django 2.1 on 2018-10-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterModelOptions(
            name='foundation',
            options={'verbose_name_plural': 'Foundation'},
        ),
        migrations.AlterModelOptions(
            name='founder',
            options={'verbose_name_plural': 'Founder'},
        ),
    ]
